# https://github.com/landfillbaby/png2webp/blob/main/.github/workflows/update-submodules.yml
name: Update submodule
on:
  schedule: [cron: 0 10 * * *]
  workflow_dispatch:
jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0
        token: ${{secrets.PUSH_TOKEN}}
   # - name: Import GPG key
   #   uses: crazy-max/ghaction-import-gpg@v5
    #  with:
     #   gpg_private_key: ${{secrets.GPG_PRIVATE_KEY}}
      #  passphrase: ${{secrets.GPG_PASS}}
       # git_user_signingkey: true
    - uses: fregante/setup-git-user@v2
    #- name: configure git
     # run: |
      #  git config user.name "Ethan Reece (GitHub Actions)"
       # git config user.email "136941696+ethanreece-rtechnics@users.noreply.github.com"
    - name: Update submodules
      run: |
        if git commit -am"Update submodules (automated)

        $(git submodule --quiet foreach \
          'tag="$( git tag | grep ^openssl-[0-9]\d*\.[0-9]\d*\.[0-9]\d*$ | tail -n1)"
          if [ "$(git describe --tags)" != "$tag" ]; then
            git checkout --quiet "$tag"
            echo "$name" "$tag"
          fi')"
        then
          git show --raw
          git push
        fi
